version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@7.0.0
  aws-ecs: circleci/aws-ecs@3.2

commands:
  build-image: aws-ecr/build-image

workflows:
  deploy-to-development:
    jobs:
      - aws-ecr/build-and-push-image:
          name: "build-and-push-image"
          context:
            - GADGETARIUM_CONTEXT
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          account-url: AWS_ECR_URL
          create-repo: false
          dockerfile: Dockerfile
          no-output-timeout: 20m
          path: ./
          region: AWS_DEFAULT_REGION
          repo: gadgetarium-b7-repo
          skip-when-tags-exist: false
          tag: main-$CIRCLE_SHA1
          filters:
            branches:
              only:
                - main
      - aws-ecs/deploy-service-update:
          context:
            - GADGETARIUM_CONTEXT
          cluster: gadgetarium-server-cluster
          container-image-name-updates: 'container=gadgetarium-main-container,tag=${CIRCLE_SHA1}'
          family: gatgetarium-server-task
          service-name: gadgetarium-main-service
          force-new-deployment: true
          filters:
            branches:
              only:
                - main
          requires:
            - build-and-push-image