version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@7.0.0
  aws-ecs: circleci/aws-ecs@3.2

commands:
  build-image: aws-ecr/build-image

jobs:
  chmod_mvnw:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - run: ./chmod +x mvnw

workflows:
  deploy-to-development:
    jobs:
      - chmod_mvnw
      - aws-ecr/build-and-push-image:
          name: "build-and-push-image"
          context:
            - GADGETARIUM_CONTEXT
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          account-url: AWS_ECR_URL
          create-repo: false
          dockerfile: Dockerfile
          no-output-timeout: 20m
          path: ./
          region: AWS_DEFAULT_REGION
          repo: gadgetarium-b7-repo
          skip-when-tags-exist: false
          tag: main-$CIRCLE_SHA1
          filters:
            branches:
              only:
                - main
#      - aws-ecs/deploy-service-update:
#          context:
#            - TAIGAN_CONTEXT
#          cluster: taigan-backend-dev
#          container-image-name-updates: 'container=taiganbackenddevcontainer,tag=${CIRCLE_SHA1}'
#          family: taigan-backend-dev
#          service-name: taiganbackenddevservice1
#          force-new-deployment: true
#          filters:
#            branches:
#              only:
#                - main
#          requires:
#            - build-and-push-image